"use client";

import { AlertTriangle, CheckCircle2, ChevronRight, CircleUserRound, Clock3, Cloud, CloudOff, FileCheck2, History, KeyRound, LogOut, Mail, Phone, RefreshCw, Search, ShieldCheck, UserRound, Wifi } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { signOut } from "@/app/login/actions";
import type { TechnicianHistoryItem, TechnicianProfileData, TechnicianSyncData } from "@/lib/technician-account-data";

const jobStatus: Record<string, string> = { scheduled: "Planifiée", assigned: "Planifiée", en_route: "En route", arrived: "Arrivée", in_progress: "En cours", blocked: "Bloquée", completed_pending_payment: "Terminée", completed: "Terminée", cancelled: "Annulée", no_show: "Absent", interrupted: "Interrompue" };
const eventLabels: Record<string, string> = { "job.created": "Mission ajoutée", "job.precheck_completed": "Pré-contrôle envoyé", "photo.uploaded": "Photo sauvegardée", "incident.created": "Incident transmis", "incident.updated": "Incident mis à jour", "incident.resolved": "Incident résolu", "job.checklist_completed": "Checklist sauvegardée", "job.final_check_completed": "Contrôle final sauvegardé", "job.completed": "Clôture transmise" };

export function TechnicianHistoryPage({ jobs }: { jobs: TechnicianHistoryItem[] }) {
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all");
  const filtered = useMemo(() => jobs.filter((job) => (filter === "all" || (filter === "completed" ? job.status.startsWith("completed") : !job.status.startsWith("completed"))) && (!query.trim() || [job.id, job.customer, job.city].some((value) => value.toLocaleLowerCase("fr").includes(query.trim().toLocaleLowerCase("fr"))))), [jobs, query, filter]);
  const completed = jobs.filter((job) => job.status.startsWith("completed"));
  return <div className="tech-account-screen"><header className="tech-page-header"><div><span>Mes interventions</span><h1>Historique</h1><p>Retrouvez les missions et les preuves déjà enregistrées.</p></div><History size={28} /></header><section className="tech-account-summary"><div><strong>{jobs.length}</strong><span>Missions</span></div><div><strong>{completed.length}</strong><span>Terminées</span></div><div><strong>{jobs.reduce((sum, job) => sum + job.equipmentCount, 0)}</strong><span>Équipements</span></div></section><section className="tech-filter-card"><label><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Client, ville ou numéro…" /></label><div><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>Toutes</button><button className={filter === "completed" ? "active" : ""} onClick={() => setFilter("completed")}>Terminées</button><button className={filter === "active" ? "active" : ""} onClick={() => setFilter("active")}>Autres</button></div></section><section className="tech-history-list">{filtered.map((job) => <Link href={`/app/jobs/${job.id}`} key={job.id}><span className={`history-status ${job.status.startsWith("completed") ? "done" : job.status === "blocked" ? "blocked" : ""}`}>{job.status.startsWith("completed") ? <CheckCircle2 /> : job.status === "blocked" ? <AlertTriangle /> : <Clock3 />}</span><span><small>{job.date} · {job.time}</small><strong>{job.customer}</strong><p>{job.city} · {job.service}</p><em>{job.equipmentCount} équipement{job.equipmentCount > 1 ? "s" : ""}{job.incidentCount ? ` · ${job.incidentCount} incident` : ""}</em></span><span><strong>{jobStatus[job.status] ?? job.status}</strong><small>{(job.amountCents / 100).toLocaleString("fr-FR", { style: "currency", currency: "EUR" })}</small></span><ChevronRight size={19} /></Link>)}</section>{!filtered.length && <TechEmpty icon={<History />} title="Aucune mission trouvée" text="Modifiez votre recherche ou le filtre." />}</div>;
}

export function TechnicianSyncPage({ data }: { data: TechnicianSyncData }) {
  const [online, setOnline] = useState(true); const [refreshed, setRefreshed] = useState(false);
  useEffect(() => { const update = () => setOnline(navigator.onLine); update(); window.addEventListener("online", update); window.addEventListener("offline", update); return () => { window.removeEventListener("online", update); window.removeEventListener("offline", update); }; }, []);
  const refresh = () => { setRefreshed(true); window.location.reload(); };
  return <div className="tech-account-screen"><header className="tech-page-header"><div><span>Données terrain</span><h1>Synchronisation</h1><p>Vérifiez que vos actions ont bien rejoint le serveur.</p></div><span className={`tech-network ${online ? "online" : "offline"}`}>{online ? <Wifi /> : <CloudOff />}{online ? "En ligne" : "Hors ligne"}</span></header><section className={`sync-health-card ${data.failed ? "danger" : data.pending ? "pending" : "ready"}`}><span>{data.failed ? <AlertTriangle /> : data.pending ? <RefreshCw /> : <Cloud />}</span><div><strong>{data.failed ? "Une action nécessite de l’aide" : data.pending ? `${data.pending} action${data.pending > 1 ? "s" : ""} en attente` : "Tout est synchronisé"}</strong><p>{online ? "Les données sont enregistrées sur le serveur et les intégrations externes sont traitées séparément." : "Les écrans déjà chargés restent visibles. Reconnectez-vous avant de clôturer une mission."}</p></div><button onClick={refresh} disabled={refreshed}><RefreshCw />Actualiser</button></section><section className="tech-account-summary sync"><div><strong>{data.pending}</strong><span>En attente</span></div><div><strong>{data.processed}</strong><span>Transmises</span></div><div><strong>{data.failed}</strong><span>En erreur</span></div></section><div className="tech-section-label"><span>Activité récente</span><small>{data.events.length} événements</small></div><section className="tech-sync-events">{data.events.map((event) => <article key={event.id}><span className={`sync-event-icon ${event.status}`} >{event.status === "processed" ? <CheckCircle2 /> : event.status === "dead" ? <AlertTriangle /> : <RefreshCw />}</span><div><strong>{eventLabels[event.type] ?? event.type}</strong><small>{event.createdAt}{event.processedAt ? ` · synchronisé ${event.processedAt}` : ""}</small>{event.error && <p>{event.error}</p>}</div><span className={`sync-event-status ${event.status}`}>{event.status === "processed" ? "Envoyé" : event.status === "dead" ? "Erreur" : "En attente"}</span></article>)}</section>{!data.events.length && <TechEmpty icon={<Cloud />} title="Aucune activité à synchroniser" text="Les prochaines actions terrain apparaîtront ici." />}</div>;
}

export function TechnicianProfilePage({ profile }: { profile: TechnicianProfileData }) {
  const expiring = profile.documentDaysLeft !== undefined && profile.documentDaysLeft <= 30;
  return <div className="tech-account-screen"><header className="tech-page-header"><div><span>Mon compte</span><h1>Profil</h1><p>Identité professionnelle et sécurité du compte.</p></div><CircleUserRound size={30} /></header><section className="tech-profile-card"><span>{profile.initials}</span><div><h2>{profile.name}</h2><p>{profile.workerType === "subcontractor" ? `Sous-traitant${profile.company ? ` · ${profile.company}` : ""}` : "Technicien interne"}</p></div><span className="profile-active"><i />Compte actif</span></section><section className="tech-account-summary"><div><strong>{profile.totalJobs}</strong><span>Missions</span></div><div><strong>{profile.equipmentServiced}</strong><span>Équipements traités</span></div><div><strong>{profile.incidentCount}</strong><span>Incidents déclarés</span></div></section><section className="tech-profile-section"><header><UserRound /><div><span>Coordonnées</span><h2>Informations du compte</h2></div></header><dl><div><dt><Mail />E-mail professionnel</dt><dd>{profile.email}</dd></div><div><dt><Phone />Téléphone</dt><dd>{profile.phone || "Non renseigné"}</dd></div><div><dt><FileCheck2 />Échéance documentaire</dt><dd className={expiring ? "warning" : ""}>{profile.documentExpiry || "Non renseignée"}{profile.documentDaysLeft !== undefined && ` · ${profile.documentDaysLeft} jours`}</dd></div>{profile.registrationNumber && <div><dt><ShieldCheck />Immatriculation</dt><dd>{profile.registrationNumber}</dd></div>}</dl></section><section className="tech-profile-section security"><header><KeyRound /><div><span>Sécurité</span><h2>Accès à l’application</h2></div></header><div className="security-row"><ShieldCheck /><div><strong>Session protégée</strong><p>Accès limité à votre organisation et à vos missions affectées. La production utilisera un compte sur invitation et une passkey liée à votre appareil.</p></div></div><form action={signOut}><button type="submit"><LogOut />Se déconnecter de cet appareil</button></form></section>{profile.notes && <section className="tech-profile-note"><strong>Note administrative</strong><p>{profile.notes}</p></section>}</div>;
}

function TechEmpty({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="tech-account-empty"><span>{icon}</span><strong>{title}</strong><p>{text}</p></div>; }
