"use client";

import { AlertTriangle, Bell, CheckCircle2, ChevronDown, ChevronRight, Clock3, ImageIcon, Menu, Search, ShieldAlert, UserRound, X } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import { signOut } from "@/app/login/actions";
import { AdminSidebar } from "@/components/admin/admin-jobs-page";
import type { AdminIncident } from "@/lib/incident-data";

const statusLabels: Record<string, string> = { open: "Ouvert", in_review: "En revue", action_required: "Action requise", resolved: "Résolu", closed_no_action: "Clos sans action" };
const severityLabels: Record<string, string> = { information: "Information", minor: "Mineur", critical: "Critique" };
const typeLabels: Record<string, string> = { preexisting_damage: "Dommage existant", preexisting_leak: "Fuite existante", error_code: "Code erreur", abnormal_noise: "Bruit anormal", no_power_or_no_start: "Ne démarre pas", access_impossible: "Accès impossible", broken_clip: "Clip cassé", accidental_water: "Eau accidentelle", customer_property_damage: "Dommage client", drain_issue: "Évacuation", incomplete_access: "Accès partiel", final_test_failed: "Échec test final", other: "Autre" };
const momentLabels: Record<string, string> = { before: "Avant", during: "Pendant", after: "Après" };

export function AdminIncidentsPage({ incidents: initialIncidents, canOverride }: { incidents: AdminIncident[]; canOverride: boolean }) {
  const router = useRouter(); const [incidents, setIncidents] = useState(initialIncidents); const [sidebarOpen, setSidebarOpen] = useState(false); const [query, setQuery] = useState(""); const [status, setStatus] = useState("active"); const [severity, setSeverity] = useState("all"); const [selected, setSelected] = useState<AdminIncident | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const filtered = useMemo(() => incidents.filter((incident) => (status === "all" || status === "active" ? status === "all" || !["resolved", "closed_no_action"].includes(incident.status) : incident.status === status) && (severity === "all" || incident.severity === severity) && (!query.trim() || [incident.publicCode, incident.jobCode, incident.customer, incident.description, incident.technician].some((value) => value.toLowerCase().includes(query.toLowerCase().trim())))), [incidents, query, severity, status]);
  const updateIncident = async (changes: { status?: string; closureOverride?: boolean }) => {
    if (!selected) return; setSaving(true); setError("");
    try {
      const response = await fetch(`/api/admin/incidents/${selected.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(changes) });
      const result = await response.json() as { error?: string };
      if (!response.ok) throw new Error(result.error ?? "Mise à jour impossible.");
      const updated = { ...selected, ...changes }; setSelected(updated); setIncidents((current) => current.map((incident) => incident.id === updated.id ? updated : incident)); router.refresh();
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Mise à jour impossible."); }
    finally { setSaving(false); }
  };
  const activeCount = incidents.filter((incident) => !["resolved", "closed_no_action"].includes(incident.status)).length;
  return <div className="app-shell"><AdminSidebar open={sidebarOpen} close={() => setSidebarOpen(false)} /><main className="main"><header className="topbar"><button className="menu-button" onClick={() => setSidebarOpen(true)} aria-label="Ouvrir le menu"><Menu size={21} /></button><div className="breadcrumbs"><span>Operations</span><ChevronRight size={14} /><strong>Incidents</strong></div><div className="top-actions"><button className="icon-button" aria-label="Notifications"><Bell size={19} /></button><form action={signOut}><button className="user-menu"><span className="user-avatar">EM</span><span><strong>Emma Martin</strong><small>Administratrice</small></span><ChevronDown size={15} /></button></form></div></header><div className="content admin-incidents-content">
    <section className="page-heading"><div><p>Suivi et résolution</p><h1>Incidents <span>— traiter les alertes terrain.</span></h1></div></section>
    <section className="incident-stats"><div><span><AlertTriangle size={18} /></span><div><small>À traiter</small><strong>{activeCount}</strong></div></div><div><span><ShieldAlert size={18} /></span><div><small>Critiques ouverts</small><strong>{incidents.filter((incident) => incident.severity === "critical" && !["resolved", "closed_no_action"].includes(incident.status)).length}</strong></div></div><div><span><Clock3 size={18} /></span><div><small>En revue</small><strong>{incidents.filter((incident) => incident.status === "in_review").length}</strong></div></div><div><span><CheckCircle2 size={18} /></span><div><small>Résolus</small><strong>{incidents.filter((incident) => ["resolved", "closed_no_action"].includes(incident.status)).length}</strong></div></div></section>
    <section className="panel incident-list-panel"><div className="admin-jobs-toolbar"><div className="mini-search admin-job-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Incident, mission, client…" /></div><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="active">À traiter</option><option value="all">Tous les statuts</option>{Object.entries(statusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><select value={severity} onChange={(event) => setSeverity(event.target.value)}><option value="all">Toutes les gravités</option>{Object.entries(severityLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div><div className="incident-table-head"><span>Incident</span><span>Client et mission</span><span>Signalé par</span><span>Gravité</span><span>Statut</span><span /></div><div className="incident-rows">{filtered.map((incident) => <button onClick={() => { setSelected(incident); setError(""); }} key={incident.id}><span><strong>{incident.publicCode}</strong><small>{typeLabels[incident.type] ?? incident.type} · {momentLabels[incident.moment] ?? incident.moment}</small></span><span><strong>{incident.customer}</strong><small>{incident.jobCode} · {incident.city}</small></span><span><strong>{incident.technician}</strong><small>{incident.createdAt}</small></span><span><em className={`severity severity-${incident.severity}`}>{severityLabels[incident.severity] ?? incident.severity}</em></span><span><em className={`incident-status incident-status-${incident.status}`}>{statusLabels[incident.status] ?? incident.status}</em></span><ChevronRight size={17} /></button>)}</div>{!filtered.length && <div className="empty-state"><CheckCircle2 size={24} /><strong>Aucun incident dans cette vue</strong><p>Les filtres actuels ne retournent aucun résultat.</p></div>}<div className="table-footer"><span>{filtered.length} incident{filtered.length > 1 ? "s" : ""}</span><span>Mise à jour en temps réel</span></div></section>
  </div></main>{selected && <div className="drawer-layer"><button className="drawer-backdrop" onClick={() => setSelected(null)} aria-label="Fermer" /><aside className="drawer incident-drawer"><div className="drawer-head"><div><span>Incident</span><strong>{selected.publicCode}</strong></div><button className="icon-button" onClick={() => setSelected(null)}><X size={20} /></button></div><div className="drawer-body"><div className="incident-drawer-title"><div><em className={`severity severity-${selected.severity}`}>{severityLabels[selected.severity]}</em><em className={`incident-status incident-status-${selected.status}`}>{statusLabels[selected.status]}</em></div><h2>{typeLabels[selected.type] ?? selected.type}</h2><p>{selected.description}</p></div>{selected.photoId ? <div className="incident-photo"><Image src={`/api/photos/${selected.photoId}`} alt={`Preuve ${selected.publicCode}`} width={900} height={600} unoptimized /></div> : <div className="incident-no-photo"><ImageIcon size={22} /><span>Aucune photo jointe</span></div>}<dl className="detail-list"><div><dt>Intervention</dt><dd><Link href={`/admin/jobs/${selected.jobCode}`}>{selected.jobCode}<ChevronRight size={14} /></Link></dd></div><div><dt>Client</dt><dd>{selected.customer} · {selected.city}</dd></div><div><dt>Équipement</dt><dd>{selected.equipment ?? "Intervention globale"}</dd></div><div><dt>Déclaré par</dt><dd><UserRound size={14} />{selected.technician}</dd></div><div><dt>Moment</dt><dd>{momentLabels[selected.moment]} · {selected.createdAt}</dd></div><div><dt>Client informé</dt><dd>{selected.clientInformed ? "Oui" : "Non"}</dd></div></dl><section className="incident-workflow"><span>Traitement</span><div>{Object.entries(statusLabels).map(([value, label]) => <button type="button" className={selected.status === value ? "active" : ""} disabled={saving} onClick={() => updateIncident({ status: value })} key={value}>{selected.status === value && <CheckCircle2 size={14} />}{label}</button>)}</div></section>{selected.severity === "critical" && <label className={`override-check ${selected.closureOverride ? "checked" : ""}`}><input type="checkbox" checked={selected.closureOverride} disabled={!canOverride || saving} onChange={(event) => updateIncident({ closureOverride: event.target.checked })} /><span><CheckCircle2 size={15} /></span><div><strong>Autoriser exceptionnellement la clôture</strong><small>{canOverride ? "Cette décision est journalisée avec votre identité." : "Réservé aux administrateurs."}</small></div></label>}{error && <div className="admin-form-error"><AlertTriangle size={15} />{error}</div>}</div></aside></div>}</div>;
}
