"use client";

import { AlertTriangle, Bell, CalendarDays, ChevronDown, ChevronLeft, ChevronRight, Clock3, Menu, Plus, SlidersHorizontal, Users } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import { signOut } from "@/app/login/actions";
import { AdminSidebar } from "@/components/admin/admin-jobs-page";
import type { AdminJobListItem, AdminTechnicianOption } from "@/lib/admin-jobs-data";

const dayNames = ["Lun", "Mar", "Mer", "Jeu", "Ven", "Sam", "Dim"];
const statusOptions = ["Tous les statuts", "Planifiée", "En route", "Arrivée", "En cours", "Bloquée", "Terminée"];
const slug = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replaceAll(" ", "-").replaceAll("·", "");
const dateFromIso = (value: string) => new Date(`${value}T12:00:00`);
const isoDate = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const addDays = (value: string, days: number) => { const date = dateFromIso(value); date.setDate(date.getDate() + days); return isoDate(date); };
const minutes = (value: string) => Number(value.slice(0, 2)) * 60 + Number(value.slice(3, 5));
const formatDay = (value: string, long = false) => new Intl.DateTimeFormat("fr-FR", long ? { weekday: "long", day: "numeric", month: "long", year: "numeric" } : { day: "2-digit", month: "short" }).format(dateFromIso(value));

function startOfWeek(value: string) {
  const date = dateFromIso(value); const day = date.getDay() || 7; date.setDate(date.getDate() - day + 1); return isoDate(date);
}

function hasConflict(job: AdminJobListItem, jobs: AdminJobListItem[]) {
  if (!job.technicianId) return false;
  return jobs.some((other) => other.id !== job.id && other.technicianId === job.technicianId && other.scheduledDate === job.scheduledDate && minutes(other.startTime) < minutes(job.endTime) && minutes(other.endTime) > minutes(job.startTime));
}

export function AdminCalendarPage({ jobs, technicians, today }: { jobs: AdminJobListItem[]; technicians: AdminTechnicianOption[]; today: string }) {
  const [sidebarOpen, setSidebarOpen] = useState(false); const [view, setView] = useState<"day" | "week">("week"); const [selectedDate, setSelectedDate] = useState(today); const [technicianId, setTechnicianId] = useState("all"); const [status, setStatus] = useState("Tous les statuts");
  const weekStart = startOfWeek(selectedDate); const weekDays = Array.from({ length: 7 }, (_, index) => addDays(weekStart, index));
  const visibleJobs = useMemo(() => jobs.filter((job) => (technicianId === "all" || job.technicianId === technicianId) && (status === "Tous les statuts" || job.status.startsWith(status))), [jobs, status, technicianId]);
  const dayJobs = visibleJobs.filter((job) => job.scheduledDate === selectedDate);
  const periodJobs = view === "week" ? visibleJobs.filter((job) => weekDays.includes(job.scheduledDate)) : dayJobs;
  const lanes = technicianId === "all" ? [...technicians, { id: "unassigned", name: "Non attribuées", role: "" }] : technicians.filter((entry) => entry.id === technicianId);
  const navigate = (direction: number) => setSelectedDate(addDays(selectedDate, direction * (view === "week" ? 7 : 1)));
  return <div className="app-shell"><AdminSidebar open={sidebarOpen} close={() => setSidebarOpen(false)} /><main className="main"><header className="topbar"><button className="menu-button" onClick={() => setSidebarOpen(true)} aria-label="Ouvrir le menu"><Menu size={21} /></button><div className="breadcrumbs"><span>Operations</span><ChevronRight size={14} /><strong>Planning</strong></div><div className="top-actions"><button className="icon-button" aria-label="Notifications"><Bell size={19} /></button><form action={signOut}><button className="user-menu"><span className="user-avatar">EM</span><span><strong>Emma Martin</strong><small>Administratrice</small></span><ChevronDown size={15} /></button></form></div></header><div className="content admin-calendar-content">
    <section className="page-heading"><div><p>Organisation terrain</p><h1>Planning <span>— visualiser la charge de l’équipe.</span></h1></div><Link className="primary-button" href="/admin/jobs"><Plus size={17} />Nouvelle intervention</Link></section>
    <section className="calendar-controls"><div className="calendar-navigation"><button className="secondary-button" onClick={() => setSelectedDate(today)}>Aujourd’hui</button><button className="icon-button" onClick={() => navigate(-1)} aria-label="Période précédente"><ChevronLeft size={18} /></button><button className="icon-button" onClick={() => navigate(1)} aria-label="Période suivante"><ChevronRight size={18} /></button><strong>{view === "week" ? `${formatDay(weekStart)} – ${formatDay(addDays(weekStart, 6))}` : formatDay(selectedDate, true)}</strong></div><div className="calendar-filters"><SlidersHorizontal size={16} /><select value={technicianId} onChange={(event) => setTechnicianId(event.target.value)}><option value="all">Toute l’équipe</option>{technicians.map((entry) => <option value={entry.id} key={entry.id}>{entry.name}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)}>{statusOptions.map((entry) => <option key={entry}>{entry}</option>)}</select><div className="calendar-view-toggle"><button className={view === "day" ? "active" : ""} onClick={() => setView("day")}>Jour</button><button className={view === "week" ? "active" : ""} onClick={() => setView("week")}>Semaine</button></div></div></section>
    <section className="calendar-summary"><span><CalendarDays size={16} /><strong>{periodJobs.length}</strong> interventions</span><span><Users size={16} /><strong>{technicians.length}</strong> techniciens actifs</span><span><Clock3 size={16} /><strong>{periodJobs.reduce((total, job) => total + Math.max(0, minutes(job.endTime) - minutes(job.startTime)), 0) / 60} h</strong> planifiées</span><span className="calendar-conflict-summary"><AlertTriangle size={16} /><strong>{periodJobs.filter((job) => hasConflict(job, periodJobs)).length}</strong> conflit{periodJobs.filter((job) => hasConflict(job, periodJobs)).length > 1 ? "s" : ""}</span></section>
    {view === "week" ? <section className="panel week-calendar"><div className="week-calendar-head"><span />{weekDays.map((day, index) => <button className={day === today ? "today" : ""} onClick={() => { setSelectedDate(day); setView("day"); }} key={day}><span>{dayNames[index]}</span><strong>{dateFromIso(day).getDate()}</strong></button>)}</div><div className="week-calendar-body"><div className="week-team-label"><Users size={17} /><span>Équipe</span></div>{weekDays.map((day) => <div className={`week-day-column ${day === today ? "today" : ""}`} key={day}>{visibleJobs.filter((job) => job.scheduledDate === day).sort((a, b) => a.startTime.localeCompare(b.startTime)).map((job) => <Link className={`calendar-job-card status-card-${slug(job.status)} ${hasConflict(job, visibleJobs) ? "conflict" : ""}`} href={`/admin/jobs/${job.id}`} key={job.id}><time>{job.startTime}–{job.endTime}</time><strong>{job.customer}</strong><span>{job.city} · {job.equipmentCount} split{job.equipmentCount > 1 ? "s" : ""}</span><small>{job.technician}</small>{hasConflict(job, visibleJobs) && <em><AlertTriangle size={11} />Chevauchement</em>}</Link>)}{!visibleJobs.some((job) => job.scheduledDate === day) && <button className="empty-calendar-slot" onClick={() => { setSelectedDate(day); setView("day"); }}><Plus size={15} />Créneau libre</button>}</div>)}</div></section> : <section className="panel day-calendar"><div className="day-calendar-head" style={{ gridTemplateColumns: `72px repeat(${lanes.length},minmax(180px,1fr))` }}><span>Horaire</span>{lanes.map((technician) => <div key={technician.id}><span className="mini-avatar">{technician.name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</span><strong>{technician.name}</strong></div>)}</div><div className="day-calendar-body" style={{ gridTemplateColumns: `72px repeat(${lanes.length},minmax(180px,1fr))` }}><div className="time-axis">{Array.from({ length: 13 }, (_, index) => <span style={{ top: `${(index / 12) * 100}%` }} key={index}>{String(index + 7).padStart(2, "0")}:00</span>)}</div>{lanes.map((technician) => <div className="technician-lane" key={technician.id}>{Array.from({ length: 13 }, (_, index) => <i style={{ top: `${(index / 12) * 100}%` }} key={index} />)}{dayJobs.filter((job) => technician.id === "unassigned" ? !job.technicianId : job.technicianId === technician.id).map((job) => { const top = Math.max(0, ((minutes(job.startTime) - 420) / 720) * 100); const height = Math.max(7, ((minutes(job.endTime) - minutes(job.startTime)) / 720) * 100); return <Link className={`day-job status-card-${slug(job.status)} ${hasConflict(job, dayJobs) ? "conflict" : ""}`} style={{ top: `${top}%`, height: `${height}%` }} href={`/admin/jobs/${job.id}`} key={job.id}><time>{job.startTime}</time><strong>{job.customer}</strong><span>{job.city} · {job.equipmentCount} split{job.equipmentCount > 1 ? "s" : ""}</span></Link>; })}</div>)}</div></section>}
    <div className="calendar-legend"><span><i className="planned" />Planifiée</span><span><i className="active" />En cours</span><span><i className="blocked" />Bloquée</span><span><i className="completed" />Terminée</span><span><i className="conflict" />Conflit de créneau</span></div>
  </div></main></div>;
}
