"use client";

import { AlertTriangle, Bell, CheckCircle2, ChevronDown, ChevronRight, Clock3, Menu, RefreshCw, ServerCog, Webhook } from "lucide-react";
import { useState } from "react";
import { signOut } from "@/app/login/actions";
import { AdminSidebar } from "@/components/admin/admin-jobs-page";
import type { IntegrationOverview } from "@/lib/integration-data";

const labels: Record<string, string> = { pending: "En attente", processing: "En cours", processed: "Traité", dead: "En échec" };
const eventLabels: Record<string, string> = { "job.created": "Intervention créée", "job.precheck_completed": "Pré-contrôle terminé", "photo.uploaded": "Photo ajoutée", "incident.created": "Incident créé", "incident.updated": "Incident mis à jour", "incident.resolved": "Incident résolu", "job.checklist_completed": "Checklist terminée", "job.final_check_completed": "Contrôle final terminé", "job.completed": "Intervention terminée" };

export function AdminIntegrationsPage({ overview }: { overview: IntegrationOverview }) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  return <div className="app-shell"><AdminSidebar open={sidebarOpen} close={() => setSidebarOpen(false)} /><main className="main"><header className="topbar"><button className="menu-button" onClick={() => setSidebarOpen(true)} aria-label="Ouvrir le menu"><Menu size={21} /></button><div className="breadcrumbs"><span>Operations</span><ChevronRight size={14} /><strong>Intégrations</strong></div><div className="top-actions"><button className="icon-button" aria-label="Notifications"><Bell size={19} /></button><form action={signOut}><button className="user-menu"><span className="user-avatar">EM</span><span><strong>Emma Martin</strong><small>Administratrice</small></span><ChevronDown size={15} /></button></form></div></header><div className="content admin-integrations-content"><section className="page-heading"><div><p>Supervision technique</p><h1>Intégrations <span>— n8n, CRM et notifications.</span></h1></div></section>
    <section className={`integration-config ${overview.n8nConfigured ? "ready" : "warning"}`}><span>{overview.n8nConfigured ? <CheckCircle2 /> : <AlertTriangle />}</span><div><strong>{overview.n8nConfigured ? "Dispatcher n8n configuré" : "Configuration n8n incomplète"}</strong><p>{overview.n8nConfigured ? "Les événements peuvent être transmis avec une signature HMAC et une clé d’idempotence." : "Ajoutez N8N_WEBHOOK_URL et INTEGRATION_WEBHOOK_SECRET dans l’environnement de production."}</p></div><code>pnpm integrations:dispatch</code></section>
    <section className="resource-stats integration-stats"><div><Clock3 /><span><small>En attente</small><strong>{overview.pending}</strong></span></div><div><RefreshCw /><span><small>En traitement</small><strong>{overview.processing}</strong></span></div><div><CheckCircle2 /><span><small>Traités</small><strong>{overview.processed}</strong></span></div><div><AlertTriangle /><span><small>Abandonnés</small><strong>{overview.dead}</strong></span></div></section>
    <section className="panel integration-panel"><div className="resource-toolbar"><div><strong>Journal d’événements</strong><span>Les actions terrain restent disponibles même si n8n est indisponible</span></div><span className="integration-endpoint"><Webhook size={14} />Webhook signé</span></div><div className="integration-head"><span>Événement</span><span>Création</span><span>Tentatives</span><span>Statut</span></div><div className="integration-events">{overview.recent.map((event) => <article key={event.id}><span><ServerCog size={16} /><span><strong>{eventLabels[event.type] ?? event.type}</strong><small>{event.id}</small>{event.lastError && <em>{event.lastError}</em>}</span></span><time>{event.createdAt}</time><strong>{event.attempts}</strong><span className={`integration-status ${event.status}`}>{labels[event.status] ?? event.status}</span></article>)}</div>{!overview.recent.length && <div className="empty-state"><ServerCog size={24} /><strong>Aucun événement</strong><p>Les événements apparaîtront dès la première action métier.</p></div>}</section>
  </div></main></div>;
}
