"use client";

import { AlertTriangle, Bell, CalendarClock, CheckCircle2, ChevronDown, ChevronRight, ClipboardCheck, FileCheck2, FlaskConical, History, Mail, Menu, Phone, Search, ShieldCheck, Timer, UserRound, Users, Wrench, X } from "lucide-react";
import Link from "next/link";
import { ReactNode, useMemo, useState } from "react";
import { signOut } from "@/app/login/actions";
import { AdminSidebar } from "@/components/admin/admin-jobs-page";
import type { AdminProduct, AdminProtocol, AdminTechnician, QualityJob } from "@/lib/admin-resources-data";

function AdminResourceShell({ title, eyebrow, description, children }: { title: string; eyebrow: string; description: string; children: ReactNode }) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  return <div className="app-shell"><AdminSidebar open={sidebarOpen} close={() => setSidebarOpen(false)} /><main className="main"><header className="topbar"><button className="menu-button" onClick={() => setSidebarOpen(true)} aria-label="Ouvrir le menu"><Menu size={21} /></button><div className="breadcrumbs"><span>Operations</span><ChevronRight size={14} /><strong>{title}</strong></div><div className="top-actions"><button className="icon-button" aria-label="Notifications"><Bell size={19} /></button><form action={signOut}><button className="user-menu"><span className="user-avatar">EM</span><span><strong>Emma Martin</strong><small>Administratrice</small></span><ChevronDown size={15} /></button></form></div></header><div className="content admin-resource-content"><section className="page-heading"><div><p>{eyebrow}</p><h1>{title} <span>— {description}</span></h1></div></section>{children}</div></main></div>;
}

const initials = (name: string) => name.split(" ").map((part) => part[0]).join("").slice(0, 2);
const statusLabels: Record<string, string> = { scheduled: "Planifiée", assigned: "Planifiée", en_route: "En route", arrived: "Arrivée", in_progress: "En cours", blocked: "Bloquée", completed_pending_payment: "Terminée · paiement", completed: "Terminée", interrupted: "Interrompue", no_show: "Absent" };

export function AdminTechniciansPage({ technicians }: { technicians: AdminTechnician[] }) {
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState<AdminTechnician>();
  const filtered = useMemo(() => technicians.filter((item) => !query.trim() || [item.name, item.email, item.phone, item.company].some((value) => value?.toLocaleLowerCase("fr").includes(query.trim().toLocaleLowerCase("fr")))), [technicians, query]);
  const completed = technicians.reduce((sum, item) => sum + item.completedJobs, 0); const total = technicians.reduce((sum, item) => sum + item.totalJobs, 0);
  return <AdminResourceShell title="Techniciens" eyebrow="Équipe terrain" description="charge, activité et conformité."><section className="resource-stats"><div><Users /><span><small>Équipe active</small><strong>{technicians.length}</strong></span></div><div><CalendarClock /><span><small>Missions à venir</small><strong>{technicians.reduce((sum, item) => sum + item.upcomingJobs, 0)}</strong></span></div><div><CheckCircle2 /><span><small>Taux terminé</small><strong>{total ? Math.round(completed / total * 100) : 0}%</strong></span></div><div><AlertTriangle /><span><small>Documents à surveiller</small><strong>{technicians.filter((item) => item.documentDaysLeft !== undefined && item.documentDaysLeft <= 30).length}</strong></span></div></section><section className="panel resource-panel"><div className="resource-toolbar"><div><strong>Équipe opérationnelle</strong><span>{filtered.length} profil{filtered.length > 1 ? "s" : ""}</span></div><label className="mini-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Nom, e-mail, téléphone…" /></label></div><div className="technician-grid">{filtered.map((item) => <button key={item.id} onClick={() => setSelected(item)}><span className="resource-avatar">{initials(item.name)}</span><span className="technician-card-name"><strong>{item.name}</strong><small>{item.workerType === "subcontractor" ? "Sous-traitant" : "Équipe interne"}</small></span><span className={`document-badge ${item.documentDaysLeft !== undefined && item.documentDaysLeft <= 30 ? "warning" : ""}`}>{item.documentDaysLeft === undefined ? "Document absent" : item.documentDaysLeft < 0 ? "Document expiré" : `${item.documentDaysLeft} j restants`}</span><span className="technician-card-metrics"><span><strong>{item.upcomingJobs}</strong><small>à venir</small></span><span><strong>{item.completedJobs}</strong><small>terminées</small></span><span><strong>{item.openIncidents}</strong><small>incidents</small></span></span><ChevronRight size={17} /></button>)}</div>{!filtered.length && <Empty />}</section>{selected && <TechnicianDrawer technician={selected} close={() => setSelected(undefined)} />}</AdminResourceShell>;
}

function TechnicianDrawer({ technician, close }: { technician: AdminTechnician; close: () => void }) { return <div className="drawer-layer"><button className="drawer-backdrop" onClick={close} aria-label="Fermer" /><aside className="drawer"><div className="drawer-head"><div><span>Profil terrain</span><strong>{technician.name}</strong></div><button className="icon-button" onClick={close}><X size={19} /></button></div><div className="drawer-body"><div className="resource-profile-head"><span>{initials(technician.name)}</span><div><h2>{technician.name}</h2><p>{technician.workerType === "subcontractor" ? `Sous-traitant${technician.company ? ` · ${technician.company}` : ""}` : "Technicien interne"}</p></div></div><dl className="detail-list"><div><dt><Mail size={13} />E-mail</dt><dd>{technician.email}</dd></div><div><dt><Phone size={13} />Téléphone</dt><dd>{technician.phone || "Non renseigné"}</dd></div><div><dt><FileCheck2 size={13} />Échéance documentaire</dt><dd>{technician.documentExpiry || "Non renseignée"}</dd></div></dl><div className="resource-drawer-stats"><div><strong>{technician.totalJobs}</strong><span>Missions confiées</span></div><div><strong>{technician.completedJobs}</strong><span>Missions terminées</span></div><div><strong>{technician.openIncidents}</strong><span>Incidents ouverts</span></div></div>{technician.notes && <div className="resource-callout"><strong>Note interne</strong><p>{technician.notes}</p></div>}</div></aside></div>; }

export function AdminQualityPage({ jobs }: { jobs: QualityJob[] }) {
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all");
  const filtered = useMemo(() => jobs.filter((job) => (filter === "all" || (filter === "complete" ? job.score === 100 : filter === "attention" ? job.score < 100 && job.score > 0 : job.score === 0)) && (!query.trim() || [job.id, job.customer, job.technician].some((value) => value.toLocaleLowerCase("fr").includes(query.trim().toLocaleLowerCase("fr"))))), [jobs, query, filter]);
  const complete = jobs.filter((job) => job.score === 100).length; const attention = jobs.filter((job) => job.incidentCount > 0 || (job.status.startsWith("completed") && job.score < 100)).length;
  return <AdminResourceShell title="Contrôle qualité" eyebrow="Conformité des interventions" description="preuves, checklist et validation finale."><section className="resource-stats"><div><ShieldCheck /><span><small>Dossiers suivis</small><strong>{jobs.length}</strong></span></div><div><CheckCircle2 /><span><small>Conformité complète</small><strong>{complete}</strong></span></div><div><AlertTriangle /><span><small>À contrôler</small><strong>{attention}</strong></span></div><div><ClipboardCheck /><span><small>Score moyen</small><strong>{jobs.length ? Math.round(jobs.reduce((sum, job) => sum + job.score, 0) / jobs.length) : 0}%</strong></span></div></section><section className="panel resource-panel"><div className="resource-toolbar"><div><strong>Dossiers d’intervention</strong><span>{filtered.length} résultat{filtered.length > 1 ? "s" : ""}</span></div><label className="mini-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Intervention, client, technicien…" /></label><select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">Tous les dossiers</option><option value="complete">Conformes</option><option value="attention">Incomplets</option><option value="empty">Non démarrés</option></select></div><div className="quality-table-head"><span>Intervention</span><span>Technicien</span><span>Preuves</span><span>Checklist</span><span>Test final</span><span>Score</span><span /></div><div className="quality-rows">{filtered.map((job) => <Link href={`/admin/jobs/${job.id}`} key={job.id}><span><strong>{job.id}</strong><small>{job.customer} · {job.date || "Non planifiée"}</small></span><span><strong>{job.technician}</strong><small>{statusLabels[job.status] ?? job.status}</small></span><QualityCount value={job.beforePhotos + job.afterPhotos} expected={job.equipmentCount * 7} /><QualityCount value={job.checklistResponses} expected={job.checklistExpected} /><QualityCount value={job.passedChecks} expected={job.equipmentCount} /><span className={`quality-score ${job.score === 100 ? "complete" : job.score > 0 ? "partial" : "empty"}`}>{job.score}%</span><ChevronRight size={17} /></Link>)}</div>{!filtered.length && <Empty />}</section></AdminResourceShell>;
}
function QualityCount({ value, expected }: { value: number; expected: number }) { const complete = expected > 0 && value >= expected; return <span className={`quality-count ${complete ? "complete" : ""}`}><strong>{value}/{expected}</strong><small>{complete ? "Complet" : "À compléter"}</small></span>; }

export function AdminProductsPage({ products, protocols }: { products: AdminProduct[]; protocols: AdminProtocol[] }) {
  const [selectedProduct, setSelectedProduct] = useState<AdminProduct>(); const [selectedProtocol, setSelectedProtocol] = useState<AdminProtocol>();
  return <AdminResourceShell title="Produits & protocoles" eyebrow="Référentiel qualité" description="consignes terrain et versions actives."><section className="resource-stats"><div><FlaskConical /><span><small>Produits actifs</small><strong>{products.filter((item) => item.active).length}</strong></span></div><div><Wrench /><span><small>Utilisations tracées</small><strong>{products.reduce((sum, item) => sum + item.usageCount, 0)}</strong></span></div><div><ClipboardCheck /><span><small>Protocoles</small><strong>{protocols.length}</strong></span></div><div><ShieldCheck /><span><small>Étapes critiques</small><strong>{protocols.filter((item) => item.active).reduce((sum, item) => sum + item.criticalCount, 0)}</strong></span></div></section><div className="products-layout"><section className="panel resource-panel"><div className="resource-toolbar"><div><strong>Produits terrain</strong><span>Consignes actuellement disponibles</span></div></div><div className="product-cards">{products.map((product) => <button onClick={() => setSelectedProduct(product)} key={product.id}><span className="product-icon"><FlaskConical /></span><span><em className={product.active ? "active" : ""}>{product.active ? "Actif" : "Archivé"}</em><strong>{product.name}</strong><small>{product.manufacturer || "Fabricant non renseigné"}</small></span><span><strong>{product.contactTime ?? 0} min</strong><small>Temps de contact</small></span><ChevronRight size={17} /></button>)}</div></section><section className="panel resource-panel"><div className="resource-toolbar"><div><strong>Protocoles versionnés</strong><span>Modèles figés pour chaque mission</span></div></div><div className="protocol-cards">{protocols.map((protocol) => <button onClick={() => setSelectedProtocol(protocol)} key={protocol.id}><span><ClipboardCheck /></span><div><em className={protocol.active ? "active" : ""}>{protocol.active ? "Version active" : "Inactive"}</em><strong>{protocol.name} · v{protocol.version}</strong><small>{protocol.itemCount} étapes · {protocol.criticalCount} critiques</small></div><ChevronRight size={17} /></button>)}</div></section></div>{selectedProduct && <ProductDrawer product={selectedProduct} close={() => setSelectedProduct(undefined)} />}{selectedProtocol && <ProtocolDrawer protocol={selectedProtocol} close={() => setSelectedProtocol(undefined)} />}</AdminResourceShell>;
}
function ProductDrawer({ product, close }: { product: AdminProduct; close: () => void }) { return <ResourceDrawer label="Fiche produit" title={product.name} close={close}><dl className="detail-list"><div><dt><UserRound size={13} />Fabricant</dt><dd>{product.manufacturer || "Non renseigné"}</dd></div><div><dt><Timer size={13} />Temps de contact</dt><dd>{product.contactTime ?? 0} minutes</dd></div><div><dt><History size={13} />Utilisation</dt><dd>{product.usageCount} intervention{product.usageCount > 1 ? "s" : ""} · {product.quantityMl} ml tracés</dd></div></dl><div className="resource-callout"><strong>Mode d’emploi</strong><p>{product.instructions}</p></div><div className="resource-callout"><strong>Rinçage</strong><p>{product.rinseRule}</p></div>{product.safetyNotes && <div className="resource-callout warning"><strong>Sécurité</strong><p>{product.safetyNotes}</p></div>}</ResourceDrawer>; }
function ProtocolDrawer({ protocol, close }: { protocol: AdminProtocol; close: () => void }) { return <ResourceDrawer label="Protocole versionné" title={`${protocol.name} · v${protocol.version}`} close={close}><div className="protocol-summary"><span className={protocol.active ? "active" : ""}>{protocol.active ? "Version active" : "Version inactive"}</span><p>Cette version est figée dans chaque intervention lors du démarrage.</p></div><ol className="protocol-steps">{protocol.items.map((item, index) => <li key={`${item.label}-${index}`}><span>{index + 1}</span><div><strong>{item.label}</strong><small>{item.critical ? "Étape critique obligatoire" : item.required ? "Obligatoire" : "Optionnelle"}</small></div>{item.critical && <ShieldCheck size={16} />}</li>)}</ol></ResourceDrawer>; }
function ResourceDrawer({ label, title, close, children }: { label: string; title: string; close: () => void; children: ReactNode }) { return <div className="drawer-layer"><button className="drawer-backdrop" onClick={close} aria-label="Fermer" /><aside className="drawer"><div className="drawer-head"><div><span>{label}</span><strong>{title}</strong></div><button className="icon-button" onClick={close}><X size={19} /></button></div><div className="drawer-body">{children}</div></aside></div>; }
function Empty() { return <div className="empty-state"><Search size={24} /><strong>Aucun résultat</strong><p>Modifiez votre recherche ou le filtre.</p></div>; }
